### ISSUE TITLE
Cannot handle filenames containing spaces

### ISSUE THREAD

**Issue by spier** [spier/docx2gfm#15]
When passing a filename that contains spaces, `docx2gfm` shows a warning and creates an empty markdown file.

For example

```
$ docx2gfm -f my_\ file\ with\ spaces.docx
pandoc: my_: openBinaryFile: does not exist (No such file or directory)

---
layout: post
title: "YOUR POST TITLE"
comments: true
categories: [tag1, tag2, multi word tag]
author: <a href="link to twitter, personal blog, linkedin, etc">YOUR NAME</a>
image: "/images/own/post_directory/logo_image_NOT_SVG_FORMAT.png"
---
```

This can likely be fixed by making sure that the filename is quoted correctly when passing it along to pandoc.

**Comment by Arghriffic** [comment]
This breaks ANY file name on Windows.

**Comment by spier** [comment]
Thanks for reporting the issue @Arghriffic.

I haven't tested on Windows, so I wouldn't be surprized if there were some issues on that OS.

Can you confirm what exactly is breaking things in WIndows?
Also I deployed a new version (`0.3.0`) yesterday, in case you want to test with that.

**Comment by Arghriffic** [comment]
> 
> 
> Thanks for reporting the issue @Arghriffic.
> 
> I haven't tested on Windows, so I wouldn't be surprized if there were some issues on that OS.
> 
> Can you confirm what exactly is breaking things in WIndows? Also I deployed a new version (`0.3.0`) yesterday, in case you want to test with that.

Any file you try to open results in a pandoc "openBinaryFile: does not exist (No such file or directory)"  it does not matter what the name is.  Spaces, no Spaces, single quotes, double quotes.  Completely breaks it.

**Comment by spier** [comment]
Hm, interesting.

The way that docx2gfm calls pandoc is this:
`pandoc '<your-file-here>' --wrap=none --atx-headers -f docx -t markdown-bracketed_spans-link_attributes-smart-simple_tables -s`

I can only speculate what might cause this.

1: Would you mind trying that out directly, to see if that works?
I a wondering if maybe on Windows the pandoc CLI options are different? Although that would be surprizing.

2: Which ruby version are you using, so that I can test with that too?

Thanks again for the bug report and for your help in debugging this.
